const HOME_ROUTE = "/",
    LOGIN_ROUTE = "/login",
    HOME2_ROUTE = " /home",
    CARDS_ROUTE = "/cards",
    APPS_ROUTE = "/apps",
    DASH_ROUTE = "/dash",
    PROFILE_ROUTE = "/profile",
    TUITION_ROUTE = "/tuition",
    MOVEMENTS_ROUTE = "/movements",
    REGISTER_ROUTE = "/register",
    PAYMENTS_ROUTE = "/consultas/payments",
    STEPONE_ROUTE = "/step-one",
    CHOOSE_SCHOOL_OPTION_ROUTE = "/choose-option",
    SEARCH_SCHOOL_ROUTE = "/search",
    VIEW_SCHOOL_ROUTE = "/view-school",
    VIEW_COURSE_ROUTE = "/view-course",
    COURSES_ROUTE = "/courses",
    SEARCH_ROUTE = "/search",
    EXPLORE_ROUTE = "/explore",
    WELCOME_ROUTE = "/welcome",
    CONSULTS_ROUTE = "/consults",
    DETAILS_ROUTE = "/detailsI",
    PAY_SCHOOL_ROUTE = "/payments/pay-school",
    PAY_TRANSPORT_ROUTE = "/pay-transport",
    PAY_COURSES_ROUTE = "/pay-courses",
    PAY_FOOD_ROUTE = "/pay-food",
    TRANSFERS_ROUTE = "/transferencias/transfer",
    PAY_FIT_ROUTE = "/pay-fit",
    CARD_INFO_ROUTE = "/consultas/infoMulti",
    CONSULT_CREDITS_ROUTE = "/consultas/credits",
    CONSULT_MOVMENTS_ROUTE = "/consultas/moviments",
    ENROLLEMENTS_ROUTE = "/matricula"


export const routes = {
    CARD_INFO_ROUTE,
    PAY_SCHOOL_ROUTE,
    TRANSFERS_ROUTE,
    PAY_FOOD_ROUTE,
    PAY_TRANSPORT_ROUTE,
    PAY_COURSES_ROUTE,
    COURSES_ROUTE,
    PAY_FIT_ROUTE,
    CONSULT_CREDITS_ROUTE,
    CONSULT_MOVMENTS_ROUTE,
    WELCOME_ROUTE,
    CONSULTS_ROUTE,
    SEARCH_ROUTE,
    ENROLLEMENTS_ROUTE,
    HOME_ROUTE,
    TUITION_ROUTE,
    PAYMENTS_ROUTE,
    VIEW_SCHOOL_ROUTE,
    HOME2_ROUTE,
    CHOOSE_SCHOOL_OPTION_ROUTE,
    SEARCH_SCHOOL_ROUTE,
    VIEW_COURSE_ROUTE,
    EXPLORE_ROUTE,
    STEPONE_ROUTE,
    REGISTER_ROUTE,
    MOVEMENTS_ROUTE,
    LOGIN_ROUTE,
    DETAILS_ROUTE,
    DASH_ROUTE,
    PROFILE_ROUTE,
    CARDS_ROUTE,
    APPS_ROUTE

} as const 